version: '3.3'
services:
    database:
        container_name: database
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: testwork507
            MYSQL_USER: testwork507
            MYSQL_PASSWORD: testwork507
        ports:
          - '4306:3306'
        volumes:
          - ./mysql:/var/lib/mysql
    php:
        container_name: php
        build:
          context: ./php
          args:
            uid: 1000
            user: andrey
        volumes:
          - ./:/var/www
        depends_on:
          - database
        user: "1000:1000"
    nginx:
        container_name: nginx
        image: nginx:stable-alpine
        ports:
          - '18080:80'
        volumes:
          - ./:/var/www
          - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - php
          - database
